# Generated by Django 4.1.5 on 2023-01-17 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("snippets", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="snippet",
            options={"ordering": ("created",)},
        ),
        migrations.RemoveField(
            model_name="snippet",
            name="language",
        ),
        migrations.RemoveField(
            model_name="snippet",
            name="linenos",
        ),
        migrations.RemoveField(
            model_name="snippet",
            name="style",
        ),
    ]
